spring:
  jackson:
    serialization:
      indent_output: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
  application:
    name: pytheas

server:
  servlet:
    context-path: '/pytheas'
